#!/bin/sh
# Keep vendored submodules (plugins/aphrodite, vendor/headroom, vendor/rtk)
# tracking their remote branch tip after every checkout, so nobody has to
# remember to run `git submodule update --remote --recursive --merge` by hand.
git submodule update --init --remote --recursive --merge
